version: '3.3'

services:
  coolab-core-service:
    container_name: coolab-core-service
    image: coolab-core-service
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    ports:
      - 8080:8080
    networks:
      - network_app
    restart: unless-stopped

networks:
  network_app:
    driver: bridge
